### ISSUE TITLE
how to deal with events that have updated info

### ISSUE THREAD

**Issue by skwp** [skwp/missionclick#4]
we are currently not processing events with same uid as we have in db. does uid change when event data changes?

**Comment by p7k** [comment]
hrrm, need to look at the code to see what you mean by 'not processing events with the same uid as in db'.  i would think that we would be pretty safe by saving Event's last mod timestamp and maybe the last state of the event.  the last state is prolly an overkill at this point but would be nice to have on the page "Pasha's Death changed from 2050 to 2025."

**Comment by skwp** [comment]
actually i was thinking about versioning/state - i think it's a good idea because most of these events are pretty shittily described in the feeds. what we could do is open up the system so it would be like a wikipedia - you can come in and fix the description for the event, with rollback capability. rails has a plugin that handles that sort of thing more or less. for the future of course..

for now you're right just need to check the timestamp. my code right now checks if i have a uid in the db, i simply skip inserting the event into the db from the feed.
